const SET_USER = 'SET_USER';
const SET_SECOND_USER = 'SET_SECOND_USER';
const SET_WORDMASTER = 'SET_WORDMASTER';
const SET_OPPONENT = 'SET_OPPONENT';

export default {
  SET_USER,
  SET_SECOND_USER,
  SET_OPPONENT,
  SET_WORDMASTER,
};
